// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6FWQZ2N4LhYlbmolzj4_xZwX-cER1Pmg',
    appId: '1:728486755056:web:c793a17fde83b7ce14a035',
    messagingSenderId: '728486755056',
    projectId: 'bms-edge-a579f',
    authDomain: 'bms-edge-a579f.firebaseapp.com',
    storageBucket: 'bms-edge-a579f.firebasestorage.app',
    measurementId: 'G-840N5X521Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmXGufIKcG3AlVZaDmQwnX4GTIYmP5jXI',
    appId: '1:728486755056:android:5abff204962435d914a035',
    messagingSenderId: '728486755056',
    projectId: 'bms-edge-a579f',
    storageBucket: 'bms-edge-a579f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRAZIF6ybSXGeW64DRRER-gcBs5fG2mBU',
    appId: '1:728486755056:ios:894274aaabdecc0e14a035',
    messagingSenderId: '728486755056',
    projectId: 'bms-edge-a579f',
    storageBucket: 'bms-edge-a579f.firebasestorage.app',
    iosBundleId: 'com.example.edge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRAZIF6ybSXGeW64DRRER-gcBs5fG2mBU',
    appId: '1:728486755056:ios:894274aaabdecc0e14a035',
    messagingSenderId: '728486755056',
    projectId: 'bms-edge-a579f',
    storageBucket: 'bms-edge-a579f.firebasestorage.app',
    iosBundleId: 'com.example.edge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6FWQZ2N4LhYlbmolzj4_xZwX-cER1Pmg',
    appId: '1:728486755056:web:a7a030d3769d59a414a035',
    messagingSenderId: '728486755056',
    projectId: 'bms-edge-a579f',
    authDomain: 'bms-edge-a579f.firebaseapp.com',
    storageBucket: 'bms-edge-a579f.firebasestorage.app',
    measurementId: 'G-1C9Z70D8JB',
  );
}
